"""The person a document's ``{{user.*}}`` chips print (F344).

Night 10b: the five Branded starters (Letter, Proposal, Report, Data Sheet,
Agreement) sign with ``{{user.name}}``. Generated by the owner from the API or
the Template Studio, the chip printed the owner's name; generated by an agent
(a session's tools, an API agent) or by Auto, no person makes the call, the
chip never resolved, and the finalisation gate blocked the document. With no
person asking, the chips are now the workspace owner's, the person the agent
works for, read from the workspace row (never from a tool argument).

The local edition's operator is seeded with an address under ``.local``
(``config.LOCAL_OPERATOR_EMAIL``), which reached letters as
``local@automatos.local``. Such an address reaches no one, so ``{{user.email}}``
gives way to the brand kit's company email, and with none it is left
unresolved: a chip with a fallback prints that, one without blocks the
document, rather than printing an address nobody can write to.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional

# RFC 6762 reserves ".local" for multicast DNS: no mail is delivered under it.
UNDELIVERABLE_EMAIL_SUFFIX = ".local"


@dataclass(frozen=True)
class DocumentUser:
    """The ``user.*`` fields, read as ``build_context`` reads a ``users`` row."""

    name: str
    email: str
    username: str


def deliverable_email(email: Any, brand_kit: Dict[str, Any]) -> str:
    """``email`` when someone can write to it, else the brand kit's company email,
    else ``""`` (the chip is then unresolved). Pure."""
    text = str(email or "").strip()
    if text and not text.lower().endswith(UNDELIVERABLE_EMAIL_SUFFIX):
        return text
    company = brand_kit.get("company") if isinstance(brand_kit, dict) else None
    return str((company if isinstance(company, dict) else {}).get("email") or "").strip()


def _requester(db: Any, user_id: Optional[int]) -> Optional[Any]:
    from core.models.core import User

    return db.query(User).filter(User.id == user_id).first() if user_id else None


def document_user(db: Any, workspace: Any, user_id: Optional[int],
                  brand_kit: Dict[str, Any]) -> Optional[DocumentUser]:
    """The person who asked (``user_id``), else ``workspace``'s owner; ``None`` when neither."""
    # Imported here, as the resolver imports its models: the pure helpers stay import-light.
    from core.workspaces.owner import workspace_owner

    person = _requester(db, user_id) or workspace_owner(db, workspace)
    if person is None:
        return None
    return DocumentUser(
        name=getattr(person, "name", None) or "",
        email=deliverable_email(getattr(person, "email", None), brand_kit),
        username=getattr(person, "username", None) or "",
    )


__all__ = ["DocumentUser", "UNDELIVERABLE_EMAIL_SUFFIX", "deliverable_email", "document_user"]
