server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://142.93.49.20:3100/loki/api/v1/push

scrape_configs:
  # Orchestrator Docker container logs
  - job_name: orchestrator-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      - source_labels: [__address__]
        target_label: server
        replacement: 'orchestrator-ai'
    static_configs:
      - labels:
          job: orchestrator-logs
          server: orchestrator-ai
          __path__: /var/lib/docker/containers/*/*-json.log

  # System logs on Orchestrator server
  - job_name: orchestrator-system
    static_configs:
    - targets:
        - localhost
      labels:
        job: orchestrator-system
        server: orchestrator-ai
        __path__: /var/log/*log
