version: '3.8'

services:
  # Next.js Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: Automatos_frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_BASE_URL:-http://localhost:8001}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./logs:/app/logs
    networks:
      - frontend_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for Next.js caching
  redis_cache:
    image: redis:7-alpine
    container_name: Automatos_redis_cache
    ports:
      - "${REDIS_CACHE_PORT:-6380}:6379"
    volumes:
      - redis_cache_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_CACHE_PASSWORD:-redis_cache_123}
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_CACHE_PASSWORD:-redis_cache_123}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - frontend_network
    restart: unless-stopped
    profiles:
      - cache

volumes:
  redis_cache_data:
    driver: local

networks:
  frontend_network:
    driver: bridge 