#!/usr/bin/env python3
"""PRD-221 S6 — generate the frontend page-manifest mirror from the contract.

Reads ``orchestrator/contracts/page-manifest.json`` (the CI-validated
source of truth) and writes ``frontend/lib/generated/page-manifest.ts`` — a
typed TS const the frontend consumes for page keys, route resolution, and
quick-prompt chips. Stdlib-only and deterministic (sorted keys, no timestamps),
the dump_routes.py discipline: two runs are byte-identical, so the committed
mirror is a checkable contract (a drifted mirror fails the vitest sync test).

Usage:  python3 -m scripts.gen_page_manifest_ts        # write
        python3 -m scripts.gen_page_manifest_ts --check # exit 1 if stale
"""
from __future__ import annotations

import json
import pathlib
import sys

_ORCH = pathlib.Path(__file__).resolve().parents[1]
_MANIFEST = _ORCH / "contracts" / "page-manifest.json"
_MIRROR = _ORCH.parent / "frontend" / "lib" / "generated" / "page-manifest.ts"

_HEADER = """// AUTO-GENERATED by orchestrator/scripts/gen_page_manifest_ts.py — DO NOT EDIT.
// Source of truth: orchestrator/contracts/page-manifest.json (PRD-221 S1/S6).
// Regenerate: python3 -m scripts.gen_page_manifest_ts
"""


def render(manifest: dict) -> str:
    pages = manifest.get("pages", [])
    keys = [p["key"] for p in pages]
    key_union = " | ".join(f'"{k}"' for k in keys) or "never"

    lines = [_HEADER]
    lines.append("export interface PageQuickPrompt {")
    lines.append("  text: string")
    lines.append("  admin_only?: boolean")
    lines.append("}")
    lines.append("")
    lines.append("export interface PageManifestEntry {")
    lines.append("  key: PageKey")
    lines.append("  route: string")
    lines.append("  title: string")
    lines.append("  purpose: string")
    lines.append("  entities: string[]")
    lines.append("  tabs: string[]")
    lines.append("  actions: string[]")
    lines.append("  quick_prompts: PageQuickPrompt[]")
    lines.append("}")
    lines.append("")
    lines.append(f"export type PageKey = {key_union}")
    lines.append("")
    # Serialise the array with json.dumps for determinism, then present as TS.
    body = json.dumps(pages, indent=2, sort_keys=True, ensure_ascii=False)
    lines.append(f"export const PAGE_MANIFEST: PageManifestEntry[] = {body}")
    lines.append("")
    lines.append(
        "export function resolvePageKey(pathname: string): PageKey | \"unknown\" {"
    )
    lines.append("  let best: PageManifestEntry | undefined")
    lines.append("  for (const entry of PAGE_MANIFEST) {")
    lines.append(
        "    if (pathname === entry.route || "
        "pathname.startsWith(entry.route.replace(/\\/$/, \"\") + \"/\")) {"
    )
    lines.append(
        "      if (!best || entry.route.length > best.route.length) best = entry"
    )
    lines.append("    }")
    lines.append("  }")
    lines.append("  return best ? best.key : \"unknown\"")
    lines.append("}")
    lines.append("")
    lines.append(
        "export function getPageEntry(key: string): PageManifestEntry | undefined {"
    )
    lines.append("  return PAGE_MANIFEST.find((e) => e.key === key)")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    manifest = json.loads(_MANIFEST.read_text(encoding="utf-8"))
    rendered = render(manifest)
    check = "--check" in sys.argv
    if check:
        current = _MIRROR.read_text(encoding="utf-8") if _MIRROR.exists() else ""
        if current != rendered:
            sys.stderr.write(
                "page-manifest.ts is stale — run python3 -m scripts.gen_page_manifest_ts\n"
            )
            return 1
        return 0
    _MIRROR.parent.mkdir(parents=True, exist_ok=True)
    _MIRROR.write_text(rendered, encoding="utf-8")
    sys.stderr.write(f"wrote {_MIRROR}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
