"""PRD-251 D8 (US-301): a channel step's params, resolved from the post.

A target's ``action_plan`` holds its kind's steps as the channel registry resolved
them (``modules/socials/targets.py``), each param mapped to a source
(``channel_adapters.py``). This module turns those sources into values for one call:

* ``$copy``: the channel's own copy, else the post's base copy; ``$title``: the post's
  title; ``$option.<name>``: the target's option; ``$idempotency_key``: the target's
  key; ``$steps.<id>``: the ``id`` an earlier step returned (``step_results.py``).
* ``$media`` / ``$media[]``: the post's rendered file(s) of the target's kind (a
  video for a video, reel or short, an image for an image or carousel), in media
  order; ``$media.content_type`` and ``$media.bytes`` are facts of the first;
  ``$thumbnail``: the post's first image. A media source becomes a
  :class:`MediaParam`: the publisher stages it as a file, or links it, by the step's
  ``files`` and ``urls`` (``publish_steps.py``).
* ``a|b`` takes the first that resolves; a list resolves each item; anything else
  is passed as it is. A source that resolves to nothing leaves the param out, except
  a media param, which fails the step (:class:`SourceMissing`).

Pure: no database, no storage, no Composio.
"""
from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

from modules.socials import channel_sizes
from modules.socials.capabilities import SEEDED_CHANNELS, ChannelStep
from modules.socials.media_urls import MediaFile
from modules.socials.service import footage_generated
from modules.socials.step_results import ID
from modules.socials.step_sources import reads_steps

# The media family each post kind publishes (a content type's first part).
KIND_MEDIA: Mapping[str, Tuple[str, ...]] = MappingProxyType({
    "text": (),
    "image": ("image",),
    "carousel": ("image",),
    "video": ("video",),
    "reel": ("video",),
    "short": ("video",),
    "story": ("image", "video"),
})
IMAGE = "image"
OPTION, STEPS = "$option.", "$steps."


class SourceMissing(Exception):
    """A step needs a file the post does not have, or a value an earlier step did not return."""


class StalePlan(Exception):
    """A target's stored steps predate publishing (they say nothing of what a step returns)."""


STALE_PLAN = (
    "This channel's publish plan was saved before publishing existed: choose the post's "
    "channels again in the composer, then approve it."
)


@dataclass(frozen=True)
class MediaParam:
    """The post's file(s) a param takes: staged as a file or linked, by the step."""

    files: Tuple[MediaFile, ...]
    many: bool


@dataclass(frozen=True)
class TargetContext:
    """What a target's sources read."""

    workspace_id: Any
    post_id: Any
    toolkit: str
    post_kind: str
    copy: str
    title: str
    options: Mapping[str, Any]
    idempotency_key: str
    media: Tuple[MediaFile, ...]  # the files of the target's kind, in media order
    thumbnail: Optional[MediaFile]
    generated: bool = False  # the post's footage was generated by an AI toolkit (D12)
    setup_note: Optional[str] = None  # the channel's, named when the platform refuses our credentials


def _family(media: MediaFile) -> str:
    return (media.content_type or "").split("/", 1)[0]


def media_for(files: Sequence[MediaFile], toolkit: str, post_kind: str) -> Tuple[MediaFile, ...]:
    """The files of the target's kind, of its own size when the post rendered several
    (``channel_sizes``: the aspect closest to the channel's), in media order."""
    families = KIND_MEDIA.get(post_kind, ())
    mine = [f for f in files if _family(f) in families]
    aspect = channel_sizes.aspect_for_target([f.aspect for f in mine], toolkit, post_kind)
    return tuple(f for f in mine if aspect is None or f.aspect == aspect)


def copy_for(copy: Any, toolkit: str) -> str:
    """The channel's own copy, else the base copy."""
    copy = copy if isinstance(copy, Mapping) else {}
    channels = copy.get("channels") if isinstance(copy.get("channels"), Mapping) else {}
    return str(channels.get(toolkit) or copy.get("base") or "")


def context_for(post: Any, target: Any, files: Sequence[MediaFile]) -> TargetContext:
    """A target's context: ``files`` are the post's media (``media_urls.resolve_post_media``)."""
    return TargetContext(
        workspace_id=post.workspace_id,
        post_id=post.id,
        toolkit=target.toolkit,
        post_kind=target.post_kind,
        copy=copy_for(post.copy, target.toolkit),
        title=post.title or "",
        options=MappingProxyType(dict(target.options)),
        idempotency_key=target.idempotency_key,
        media=media_for(files, target.toolkit, target.post_kind),
        thumbnail=next((f for f in files if _family(f) == IMAGE), None),
        generated=footage_generated(post.footage),
        setup_note=_setup_note(target.toolkit),
    )


def _setup_note(toolkit: str) -> Optional[str]:
    adapter = SEEDED_CHANNELS.get(toolkit)
    return adapter.setup_note if adapter is not None else None


def steps_of(action_plan: Any) -> Tuple[ChannelStep, ...]:
    """The steps a target's ``action_plan`` holds (checked when they were stored).
    Raises :class:`StalePlan` for steps stored before publishing existed (Wave 2): they
    lack ``returns``, so every ``$steps`` source would read nothing and a status step
    would not wait. Choosing the channels again stores the current plan."""
    raw = action_plan.get("steps") if isinstance(action_plan, Mapping) else None
    if any(not isinstance(step, Mapping) or "returns" not in step for step in raw or ()):
        raise StalePlan(STALE_PLAN)
    return tuple(
        ChannelStep(
            id=str(step["id"]),
            action=str(step["action"]),
            step_class=str(step["class"]),
            params=MappingProxyType(dict(step.get("params") or {})),
            files=tuple(step.get("files") or ()),
            urls=tuple(step.get("urls") or ()),
            optional=step.get("optional") is True,
            returns=MappingProxyType(dict(step.get("returns") or {})),
            until=MappingProxyType(dict(step["until"])) if step.get("until") else None,
            permalink=step.get("permalink"),
            jpeg=tuple(step.get("jpeg") or ()),
        )
        for step in raw or ()
    )


def _media(ctx: TargetContext, ref: str) -> Any:
    first = ctx.media[0] if ctx.media else None
    if ref == "$thumbnail":
        return MediaParam((ctx.thumbnail,), many=False) if ctx.thumbnail else None
    if ref == "$media[]":
        return MediaParam(ctx.media, many=True) if ctx.media else None
    if first is None:
        return None
    facts = {"$media": MediaParam((first,), many=False), "$media.content_type": first.content_type, "$media.bytes": first.bytes}
    return facts.get(ref)


def _one(ref: str, ctx: TargetContext, outputs: Mapping[str, Mapping[str, Any]]) -> Any:
    if ref.startswith(OPTION):
        return ctx.options.get(ref[len(OPTION):])
    if ref.startswith(STEPS):
        step_id, _, name = ref[len(STEPS):].partition(".")
        return (outputs.get(step_id) or {}).get(name or ID)
    named = {
        "$copy": ctx.copy or None,
        "$title": ctx.title or None,
        "$idempotency_key": ctx.idempotency_key,
        "$generated": True if ctx.generated else None,  # otherwise the next alternative decides
    }
    return named[ref] if ref in named else _media(ctx, ref)


def _choice(value: Mapping[str, Any], ctx: TargetContext, outputs: Mapping[str, Mapping[str, Any]]) -> Any:
    """``choose``'s value when ``among`` holds it; else the first of ``else`` that
    ``among`` holds, or ``else``'s first when ``among`` is unknown."""
    chosen = resolve_value(value["choose"], ctx, outputs)
    among = resolve_value(value["among"], ctx, outputs)
    allowed = [str(item) for item in among] if isinstance(among, (list, tuple)) else None
    if allowed is None:
        return value["else"][0] if value["else"] else None
    if chosen is not None and str(chosen) in allowed:
        return chosen
    return next((item for item in value["else"] if item in allowed), None)


def resolve_value(value: Any, ctx: TargetContext, outputs: Mapping[str, Mapping[str, Any]]) -> Any:
    """One param's value from its source; ``None`` when nothing resolves."""
    if isinstance(value, Mapping):
        return _choice(value, ctx, outputs)
    if isinstance(value, (list, tuple)):
        items = [resolve_value(item, ctx, outputs) for item in value]
        items = [item for item in items if item is not None]
        return items or None
    if not isinstance(value, str) or not value.startswith("$"):
        return value
    for ref in value.split("|"):
        found = _one(ref, ctx, outputs)
        if found is not None:
            return found
    return None


def resolve_params(step: ChannelStep, ctx: TargetContext, outputs: Mapping[str, Mapping[str, Any]]) -> Dict[str, Any]:
    """The step's params, each from its source; one that resolves to nothing is left
    out, except a file or link param, or one reading what an earlier step returned
    (an X post without the media id its upload returned would publish without its
    image): those raise :class:`SourceMissing`, and the step is never called."""
    params: Dict[str, Any] = {}
    for name, source in step.params.items():
        value = resolve_value(source, ctx, outputs)
        if value is None and name in step.files + step.urls:
            wanted = " or ".join(KIND_MEDIA.get(ctx.post_kind, ())) or "media"
            raise SourceMissing(f"{step.action} needs a {wanted} file for {name}, and the post has none")
        if value is None and isinstance(source, Mapping):
            raise SourceMissing(f"{step.action}: none of {', '.join(source['else'])} is allowed for {name} on this account")
        if value is None and reads_steps(source):
            raise SourceMissing(f"{step.action}: {name} reads what an earlier step returned ({source}), and it returned nothing")
        if value is not None:
            params[name] = value
    return params
