
"""add_tool_models_and_audit_logs

Revision ID: 128a785a7681
Revises: add_workflow_indexes
Create Date: 2025-09-18 14:26:57.300319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '128a785a7681'
down_revision = 'add_workflow_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.String(length=255), nullable=False),
    sa.Column('benchmark_name', sa.String(length=255), nullable=False),
    sa.Column('benchmark_type', sa.String(length=100), nullable=False),
    sa.Column('validity_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('discriminatory_power', sa.Float(), nullable=True),
    sa.Column('overall_quality', sa.Float(), nullable=True),
    sa.Column('quality_classification', sa.String(length=50), nullable=True),
    sa.Column('assessment_data', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('capability_rating', sa.Float(), nullable=True),
    sa.Column('complexity_index', sa.Float(), nullable=True),
    sa.Column('environment_factor', sa.Float(), nullable=True),
    sa.Column('assessment_details', sa.JSON(), nullable=True),
    sa.Column('assessment_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.String(length=255), nullable=False),
    sa.Column('evaluation_type', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('detailed_results', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id')
    )
    op.create_table('external_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('knowledge_metadata', sa.JSON(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=255), nullable=False),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('emergence_score', sa.Float(), nullable=True),
    sa.Column('integration_score', sa.Float(), nullable=True),
    sa.Column('integration_classification', sa.String(length=50), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_level', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('decay_factor', sa.Float(), nullable=True),
    sa.Column('consolidation_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('immediate_memory', sa.JSON(), nullable=True),
    sa.Column('working_memory', sa.JSON(), nullable=True),
    sa.Column('short_term_memory', sa.JSON(), nullable=True),
    sa.Column('long_term_memory', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('tool_scores', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.JSON(), nullable=True),
    sa.Column('augmented_memory', sa.JSON(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('consensus_score', sa.Float(), nullable=True),
    sa.Column('coordination', sa.JSON(), nullable=True),
    sa.Column('optimization', sa.JSON(), nullable=True),
    sa.Column('optimization_config', sa.JSON(), nullable=True),
    sa.Column('field_value', sa.Float(), nullable=True),
    sa.Column('influence_weights', sa.JSON(), nullable=True),
    sa.Column('gradient', sa.JSON(), nullable=True),
    sa.Column('field_timestamp', sa.DateTime(), nullable=True),
    sa.Column('propagation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('interactions', sa.JSON(), nullable=True),
    sa.Column('emergent_effect', sa.Float(), nullable=True),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('prev_field_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('performance_data')
    op.drop_table('User')
    op.drop_table('conversations')
    op.drop_table('system_alerts')
    op.drop_table('chat_messages')
    op.drop_table('user_activities')
    op.drop_index('idx_document_chunks_document_id', table_name='document_chunks')
    op.drop_index('idx_document_chunks_embedding', table_name='document_chunks', postgresql_using='ivfflat')
    op.drop_table('document_chunks')
    op.drop_table('context_usage')
    op.drop_table('system_metrics')
    op.drop_table('agent_tools')
    op.drop_table('agent_executions')
    op.alter_column('agent_skills', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'agent_skills', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'agent_skills', 'skills', ['skill_id'], ['id'])
    op.add_column('agents', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('emergence_score', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('performance', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('reliability', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('readiness', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('coherence', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('efficiency', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('eci', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('validity', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('discriminatory_power', sa.Float(), nullable=True))
    op.alter_column('agents', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('agents', 'agent_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('agents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('agents', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('agents', 'capabilities')
    op.drop_column('agents', 'errorCount')
    op.drop_column('agents', 'averageTime')
    op.drop_column('agents', 'lastActive')
    op.drop_column('agents', 'successRate')
    op.drop_column('agents', 'totalExecutions')
    op.drop_column('agents', 'version')
    op.drop_column('agents', 'updatedAt')
    op.drop_column('agents', 'createdAt')
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('doc_metadata', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('upload_date', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('processed_date', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.alter_column('documents', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'processing'::text"))
    op.alter_column('documents', 'tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_documents_file_type', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_constraint('documents_userId_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'fileType')
    op.drop_column('documents', 'originalName')
    op.drop_column('documents', 'fileSize')
    op.drop_column('documents', 'lastAccessed')
    op.drop_column('documents', 'processedBy')
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'cloudStoragePath')
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'updatedAt')
    op.drop_column('documents', 'extractedText')
    op.drop_column('documents', 'userId')
    op.drop_column('documents', 'downloadCount')
    op.drop_column('documents', 'createdAt')
    op.alter_column('skills', 'skill_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('skills', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('users_email_key', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'password')
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'role')
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.add_column('workflows', sa.Column('owner', sa.String(length=255), nullable=True))
    op.add_column('workflows', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('workflows', sa.Column('default_policy_id', sa.String(length=128), nullable=True))
    op.add_column('workflows', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('workflows', sa.Column('expected_duration', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('complexity_score', sa.Float(), nullable=True))
    op.add_column('workflows', sa.Column('success_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'success_rate')
    op.drop_column('workflows', 'complexity_score')
    op.drop_column('workflows', 'expected_duration')
    op.drop_column('workflows', 'priority')
    op.drop_column('workflows', 'default_policy_id')
    op.drop_column('workflows', 'tags')
    op.drop_column('workflows', 'owner')
    op.add_column('users', sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.TEXT(), server_default=sa.text("'user'::text"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstName', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastName', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('users_email_key', 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'username')
    op.alter_column('skills', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('skills', 'skill_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('documents', sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('downloadCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('extractedText', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('cloudStoragePath', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('processedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('lastAccessed', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('fileSize', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('originalName', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('fileType', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('documents_userId_fkey', 'documents', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_file_type', 'documents', ['fileType'], unique=False)
    op.alter_column('documents', 'tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'processing'::text"))
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('documents', 'id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('documents', 'created_by')
    op.drop_column('documents', 'processed_date')
    op.drop_column('documents', 'upload_date')
    op.drop_column('documents', 'doc_metadata')
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'filename')
    op.add_column('agents', sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('version', sa.TEXT(), server_default=sa.text("'1.0.0'::text"), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('totalExecutions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('successRate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('lastActive', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('averageTime', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('errorCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('capabilities', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('agents', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('agents', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('agents', 'agent_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agents', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('agents', 'discriminatory_power')
    op.drop_column('agents', 'validity')
    op.drop_column('agents', 'eci')
    op.drop_column('agents', 'efficiency')
    op.drop_column('agents', 'coherence')
    op.drop_column('agents', 'readiness')
    op.drop_column('agents', 'reliability')
    op.drop_column('agents', 'performance')
    op.drop_column('agents', 'emergence_score')
    op.drop_column('agents', 'quality_score')
    op.drop_constraint(None, 'agent_skills', type_='foreignkey')
    op.drop_constraint(None, 'agent_skills', type_='foreignkey')
    op.alter_column('agent_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_skills', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('taskId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('startTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('endTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inputSize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outputSize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='agent_executions_pkey')
    )
    op.create_table('agent_tools',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('toolName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('toolType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'enabled'::text"), autoincrement=False, nullable=False),
    sa.Column('configuration', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('usageCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lastUsed', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='agent_tools_pkey')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metricType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_metrics_pkey')
    )
    op.create_table('context_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('used_in_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name='context_usage_chunk_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='context_usage_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='context_usage_pkey')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_chunks_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_chunks_pkey')
    )
    op.create_index('idx_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='user_activities_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_activities_pkey')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], name='chat_messages_conversationId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_table('system_alerts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), server_default=sa.text("'medium'::text"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_alerts_pkey')
    )
    op.create_table('conversations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'user'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key')
    )
    op.create_table('performance_data',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metricType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('timeWindow', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='performance_data_pkey')
    )
    op.drop_table('tasks')
    op.drop_table('memory_items')
    op.drop_table('integration_analyses')
    op.drop_table('external_knowledge')
    op.drop_table('evaluation_results')
    op.drop_table('component_metrics')
    op.drop_table('benchmark_assessments')
    # ### end Alembic commands ###
