
"""PostgreSQL migration - remove SQLite dependencies

Revision ID: 208275450a15
Revises: add_workflow_indexes
Create Date: 2025-09-16 22:06:16.348859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '208275450a15'
down_revision = 'add_workflow_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('priority_level', sa.String(length=50), nullable=True),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=True),
    sa.Column('auto_start', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('emergence_score', sa.Float(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('readiness', sa.Float(), nullable=True),
    sa.Column('coherence', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('eci', sa.Float(), nullable=True),
    sa.Column('validity', sa.Float(), nullable=True),
    sa.Column('discriminatory_power', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.String(length=255), nullable=False),
    sa.Column('benchmark_name', sa.String(length=255), nullable=False),
    sa.Column('benchmark_type', sa.String(length=100), nullable=False),
    sa.Column('validity_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('discriminatory_power', sa.Float(), nullable=True),
    sa.Column('overall_quality', sa.Float(), nullable=True),
    sa.Column('quality_classification', sa.String(length=50), nullable=True),
    sa.Column('assessment_data', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('capability_rating', sa.Float(), nullable=True),
    sa.Column('complexity_index', sa.Float(), nullable=True),
    sa.Column('environment_factor', sa.Float(), nullable=True),
    sa.Column('assessment_details', sa.JSON(), nullable=True),
    sa.Column('assessment_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.String(length=255), nullable=False),
    sa.Column('evaluation_type', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('detailed_results', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id')
    )
    op.create_table('external_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('knowledge_metadata', sa.JSON(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=255), nullable=False),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('emergence_score', sa.Float(), nullable=True),
    sa.Column('integration_score', sa.Float(), nullable=True),
    sa.Column('integration_classification', sa.String(length=50), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_level', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('decay_factor', sa.Float(), nullable=True),
    sa.Column('consolidation_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('retrieval_strategy', sa.String(length=100), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('performance_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('immediate_memory', sa.JSON(), nullable=True),
    sa.Column('working_memory', sa.JSON(), nullable=True),
    sa.Column('short_term_memory', sa.JSON(), nullable=True),
    sa.Column('long_term_memory', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('tool_scores', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.JSON(), nullable=True),
    sa.Column('augmented_memory', sa.JSON(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('consensus_score', sa.Float(), nullable=True),
    sa.Column('coordination', sa.JSON(), nullable=True),
    sa.Column('optimization', sa.JSON(), nullable=True),
    sa.Column('optimization_config', sa.JSON(), nullable=True),
    sa.Column('field_value', sa.Float(), nullable=True),
    sa.Column('influence_weights', sa.JSON(), nullable=True),
    sa.Column('gradient', sa.JSON(), nullable=True),
    sa.Column('field_timestamp', sa.DateTime(), nullable=True),
    sa.Column('propagation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('interactions', sa.JSON(), nullable=True),
    sa.Column('emergent_effect', sa.Float(), nullable=True),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('prev_field_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_definition', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('default_policy_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('expected_duration', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    op.create_table('workflow_agents',
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], )
    )
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('context_usage')
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('doc_metadata', sa.JSON(), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('documents', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.drop_constraint('documents_file_hash_key', 'documents', type_='unique')
    op.drop_index('idx_documents_file_type', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_file_type', 'documents', ['file_type'], unique=False)
    op.create_unique_constraint('documents_file_hash_key', 'documents', ['file_hash'])
    op.alter_column('documents', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('documents', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('documents', 'doc_metadata')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'original_filename')
    op.create_table('context_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('used_in_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name='context_usage_chunk_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='context_usage_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='context_usage_pkey')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_chunks_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_chunks_pkey')
    )
    op.create_index('idx_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.drop_table('workflow_executions')
    op.drop_table('workflow_agents')
    op.drop_table('agent_skills')
    op.drop_table('workflows')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('system_configurations')
    op.drop_table('skills')
    op.drop_table('rag_configurations')
    op.drop_table('patterns')
    op.drop_table('memory_items')
    op.drop_table('integration_analyses')
    op.drop_table('external_knowledge')
    op.drop_table('evaluation_results')
    op.drop_table('component_metrics')
    op.drop_table('benchmark_assessments')
    op.drop_table('agents')
    # ### end Alembic commands ###
