
"""add_agent_fields_and_skill_category

Revision ID: 8971278efa6b
Revises: 6203026dbac0
Create Date: 2025-07-30 18:18:16.555180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8971278efa6b'
down_revision = '6203026dbac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('priority_level', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('max_concurrent_tasks', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('auto_start', sa.Boolean(), nullable=True))
    op.add_column('skills', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'category')
    op.drop_column('agents', 'auto_start')
    op.drop_column('agents', 'max_concurrent_tasks')
    op.drop_column('agents', 'priority_level')
    # ### end Alembic commands ###
