/**
 * Glossary — plain-English definitions for the 8 core Automatos terms.
 * Used by <GlossaryTooltip> to help non-techy users orient on their first
 * sightings. PRD §1 Move 2.
 *
 * Definitions are deliberately one sentence each. Voice: direct, named,
 * no hype. Match the brand voice rules in PRD §8.3.
 */

export type GlossaryTerm =
  | 'mission'
  | 'agent'
  | 'playbook'
  | 'deliverable'
  | 'router'
  | 'skill'
  | 'handoff'
  | 't25';

export interface GlossaryEntry {
  /** The canonical term as it appears in the UI */
  label: string;
  /** One-sentence plain-English definition. No marketing copy. */
  definition: string;
  /** Optional: a worked example or analogue from a familiar tool */
  example?: string;
}

export const GLOSSARY: Record<GlossaryTerm, GlossaryEntry> = {
  mission: {
    label: 'Mission',
    definition:
      'A single piece of work you ask the platform to do, end-to-end. Has a goal, the agents that worked on it, and a record of every step.',
    example: 'msn_8f3a — "Launch · Q3 product update"',
  },
  agent: {
    label: 'Agent',
    definition:
      'A specialist worker with one job. Each agent has a role, a model behind it, and the tools it is allowed to use.',
    example: 'Sentinel reviews code. Halberd does research. Auto routes work.',
  },
  playbook: {
    label: 'Playbook',
    definition:
      'A reusable recipe for a mission. Pick a playbook, fill in the inputs, and the platform runs the same sequence of agents and tools every time.',
  },
  deliverable: {
    label: 'Deliverable',
    definition:
      'A file or document produced by a mission. Lives in /deliverables and stays linked to the mission that created it.',
    example: 'Q3-update.md, generated by mission msn_8f3a.',
  },
  router: {
    label: 'Router',
    definition:
      'The piece that picks which agent runs the next step of a mission. Uses a semantic match against past successful runs.',
  },
  skill: {
    label: 'Skill',
    definition:
      'A portable, versioned bundle of knowledge an agent can use. Skills are installable from the marketplace.',
    example: '"brand-voice-marlow" lets any agent write in your voice.',
  },
  handoff: {
    label: 'Handoff',
    definition:
      'When one agent passes the work — plus the context — to another. Logged in the audit trail.',
    example: 'Halberd → Scribe: research summary passed for drafting.',
  },
  t25: {
    label: 'T2.5',
    definition:
      'The default routing tier. T2.5 means "look up a near-match in past missions and use the agent that worked before." Higher than a cold start, lower than a fresh plan.',
  },
};
